server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/auth_db
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: 127.0.0.1:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://127.0.0.1:18081

jwt:
  # Секретный ключ HMAC-SHA256 (в base64) для подписи Access токена
  secret-key: kgy0iUhUm9BkRXwFrw8ksMpP5TmT3tE/o92K2Kjj6ys=
  access-token-expiration-ms: 900000      # (15 минут)
  refresh-token-expiration-ms: 604800000  # (7 дней)

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html