nameOverride: inventory-service
fullnameOverride: ecommerce-inventory-service

image:
  repository: ecommerce-inventory-service
  tag: latest

service:
  port: 8085

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"