nameOverride: order-service
fullnameOverride: ecommerce-order-service

image:
  repository: ecommerce-order-service
  tag: latest

service:
  port: 8086

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"