[versions]
springBoot = "3.3.4"
springCloud = "2023.0.3"
springDoc = "2.6.0"


[libraries]
# Spring Cloud BOM и Gateway
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud"}
spring-cloud-starter-gateway = { module = "org.springframework.cloud:spring-cloud-starter-gateway"}

# Swagger / OpenAPI
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springDoc"}

# Spring Boot Starters
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web"}
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator"}
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation"}
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test"}

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }